/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_ConstellationID_H_
#define	_ConstellationID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConstellationID {
	ConstellationID_unavailable	= 0,
	ConstellationID_gps	= 1,
	ConstellationID_gal	= 2,
	ConstellationID_bds	= 3,
	ConstellationID_glo	= 4
} e_ConstellationID;

/* ConstellationID */
typedef long	 ConstellationID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ConstellationID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ConstellationID;
extern const asn_INTEGER_specifics_t asn_SPC_ConstellationID_specs_1;
asn_struct_free_f ConstellationID_free;
asn_struct_print_f ConstellationID_print;
asn_constr_check_f ConstellationID_constraint;
ber_type_decoder_f ConstellationID_decode_ber;
der_type_encoder_f ConstellationID_encode_der;
xer_type_decoder_f ConstellationID_decode_xer;
xer_type_encoder_f ConstellationID_encode_xer;
oer_type_decoder_f ConstellationID_decode_oer;
oer_type_encoder_f ConstellationID_encode_oer;
per_type_decoder_f ConstellationID_decode_uper;
per_type_encoder_f ConstellationID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ConstellationID_H_ */
#include <asn_internal.h>
