/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_CoopEnhancement_H_
#define	_CoopEnhancement_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FullPrecisionInterframe.h"
#include "DifferentialMicroframe.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CoopEnhancement_PR {
	CoopEnhancement_PR_NOTHING,	/* No components present */
	CoopEnhancement_PR_fps,
	CoopEnhancement_PR_dmf
	/* Extensions may appear below */
	
} CoopEnhancement_PR;

/* CoopEnhancement */
typedef struct CoopEnhancement {
	CoopEnhancement_PR present;
	union CoopEnhancement_u {
		FullPrecisionInterframe_t	 fps;
		DifferentialMicroframe_t	 dmf;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoopEnhancement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoopEnhancement;
extern asn_CHOICE_specifics_t asn_SPC_CoopEnhancement_specs_1;
extern asn_TYPE_member_t asn_MBR_CoopEnhancement_1[2];
extern asn_per_constraints_t asn_PER_type_CoopEnhancement_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CoopEnhancement_H_ */
#include "asn_internal.h"
