/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.1.asn"
 */

#ifndef	_DifferentialOptionalContainer_H_
#define	_DifferentialOptionalContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DifferentialCarrierPhase.h"
#include "GPSDataUncertainty.h"
#include "DifferentialDoppler.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DifferentialOptionalContainer */
typedef struct DifferentialOptionalContainer {
	DifferentialCarrierPhase_t	 differentialCarrierPhase;
	GPSDataUncertainty_t	 differentialCarrierPhaseUncertainty;
	DifferentialDoppler_t	 differentialDoppler;
	GPSDataUncertainty_t	 differentialDopplerUncertainty;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DifferentialOptionalContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DifferentialOptionalContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_DifferentialOptionalContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_DifferentialOptionalContainer_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _DifferentialOptionalContainer_H_ */
#include "asn_internal.h"
