/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_DifferentialPseudorange_H_
#define	_DifferentialPseudorange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DifferentialPseudorange */
typedef long	 DifferentialPseudorange_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DifferentialPseudorange_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DifferentialPseudorange;
asn_struct_free_f DifferentialPseudorange_free;
asn_struct_print_f DifferentialPseudorange_print;
asn_constr_check_f DifferentialPseudorange_constraint;
ber_type_decoder_f DifferentialPseudorange_decode_ber;
der_type_encoder_f DifferentialPseudorange_encode_der;
xer_type_decoder_f DifferentialPseudorange_decode_xer;
xer_type_encoder_f DifferentialPseudorange_encode_xer;
oer_type_decoder_f DifferentialPseudorange_decode_oer;
oer_type_encoder_f DifferentialPseudorange_encode_oer;
per_type_decoder_f DifferentialPseudorange_decode_uper;
per_type_encoder_f DifferentialPseudorange_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DifferentialPseudorange_H_ */
#include <asn_internal.h>
