/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_DifferentialDoppler_H_
#define	_DifferentialDoppler_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DifferentialDoppler */
typedef long	 DifferentialDoppler_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DifferentialDoppler_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DifferentialDoppler;
asn_struct_free_f DifferentialDoppler_free;
asn_struct_print_f DifferentialDoppler_print;
asn_constr_check_f DifferentialDoppler_constraint;
ber_type_decoder_f DifferentialDoppler_decode_ber;
der_type_encoder_f DifferentialDoppler_encode_der;
xer_type_decoder_f DifferentialDoppler_decode_xer;
xer_type_encoder_f DifferentialDoppler_encode_xer;
oer_type_decoder_f DifferentialDoppler_decode_oer;
oer_type_encoder_f DifferentialDoppler_encode_oer;
per_type_decoder_f DifferentialDoppler_decode_uper;
per_type_encoder_f DifferentialDoppler_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DifferentialDoppler_H_ */
#include "asn_internal.h"
