/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_DifferentialID_H_
#define	_DifferentialID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DifferentialID */
typedef long	 DifferentialID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DifferentialID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DifferentialID;
asn_struct_free_f DifferentialID_free;
asn_struct_print_f DifferentialID_print;
asn_constr_check_f DifferentialID_constraint;
ber_type_decoder_f DifferentialID_decode_ber;
der_type_encoder_f DifferentialID_encode_der;
xer_type_decoder_f DifferentialID_decode_xer;
xer_type_encoder_f DifferentialID_encode_xer;
oer_type_decoder_f DifferentialID_decode_oer;
oer_type_encoder_f DifferentialID_encode_oer;
per_type_decoder_f DifferentialID_decode_uper;
per_type_encoder_f DifferentialID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DifferentialID_H_ */
#include <asn_internal.h>
