/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_Doppler_H_
#define	_Doppler_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Doppler {
	Doppler_oneMilliHertz	= 1,
	Doppler_oneHertz	= 1000
} e_Doppler;

/* Doppler */
typedef long	 Doppler_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Doppler_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Doppler;
asn_struct_free_f Doppler_free;
asn_struct_print_f Doppler_print;
asn_constr_check_f Doppler_constraint;
ber_type_decoder_f Doppler_decode_ber;
der_type_encoder_f Doppler_encode_der;
xer_type_decoder_f Doppler_decode_xer;
xer_type_encoder_f Doppler_encode_xer;
oer_type_decoder_f Doppler_decode_oer;
oer_type_encoder_f Doppler_encode_oer;
per_type_decoder_f Doppler_decode_uper;
per_type_encoder_f Doppler_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Doppler_H_ */
#include <asn_internal.h>
