/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.2.2.asn"
 */

#ifndef	_FullPrecisionID_H_
#define	_FullPrecisionID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FullPrecisionID */
typedef long	 FullPrecisionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FullPrecisionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FullPrecisionID;
asn_struct_free_f FullPrecisionID_free;
asn_struct_print_f FullPrecisionID_print;
asn_constr_check_f FullPrecisionID_constraint;
ber_type_decoder_f FullPrecisionID_decode_ber;
der_type_encoder_f FullPrecisionID_encode_der;
xer_type_decoder_f FullPrecisionID_decode_xer;
xer_type_encoder_f FullPrecisionID_encode_xer;
oer_type_decoder_f FullPrecisionID_decode_oer;
oer_type_encoder_f FullPrecisionID_encode_oer;
per_type_decoder_f FullPrecisionID_decode_uper;
per_type_encoder_f FullPrecisionID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FullPrecisionID_H_ */
#include "asn_internal.h"
