/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#include "FullPrecisionInterframe.h"

static int
memb_satelliteSignalInfo_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 8)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_satelliteSignalInfo_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..8)) */};
static asn_per_constraints_t asn_PER_type_satelliteSignalInfo_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_satelliteSignalInfo_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..8)) */};
static asn_per_constraints_t asn_PER_memb_satelliteSignalInfo_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_satelliteSignalInfo_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SatelliteSignalInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_satelliteSignalInfo_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_satelliteSignalInfo_specs_4 = {
	sizeof(struct satelliteSignalInfo),
	offsetof(struct satelliteSignalInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_satelliteSignalInfo_4 = {
	"satelliteSignalInfo",
	"satelliteSignalInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_satelliteSignalInfo_tags_4,
	sizeof(asn_DEF_satelliteSignalInfo_tags_4)
		/sizeof(asn_DEF_satelliteSignalInfo_tags_4[0]) - 1, /* 1 */
	asn_DEF_satelliteSignalInfo_tags_4,	/* Same as above */
	sizeof(asn_DEF_satelliteSignalInfo_tags_4)
		/sizeof(asn_DEF_satelliteSignalInfo_tags_4[0]), /* 2 */
	{ &asn_OER_type_satelliteSignalInfo_constr_4, &asn_PER_type_satelliteSignalInfo_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_satelliteSignalInfo_4,
	1,	/* Single element */
	&asn_SPC_satelliteSignalInfo_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_FullPrecisionInterframe_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FullPrecisionInterframe, fullPrecisionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FullPrecisionID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fullPrecisionID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FullPrecisionInterframe, cemTstamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CemTimestamp,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cemTstamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FullPrecisionInterframe, satelliteSignalInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_satelliteSignalInfo_4,
		0,
		{ &asn_OER_memb_satelliteSignalInfo_constr_4, &asn_PER_memb_satelliteSignalInfo_constr_4,  memb_satelliteSignalInfo_constraint_1 },
		0, 0, /* No default value */
		"satelliteSignalInfo"
		},
};
static const ber_tlv_tag_t asn_DEF_FullPrecisionInterframe_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FullPrecisionInterframe_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fullPrecisionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cemTstamp */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* satelliteSignalInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_FullPrecisionInterframe_specs_1 = {
	sizeof(struct FullPrecisionInterframe),
	offsetof(struct FullPrecisionInterframe, _asn_ctx),
	asn_MAP_FullPrecisionInterframe_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FullPrecisionInterframe = {
	"FullPrecisionInterframe",
	"FullPrecisionInterframe",
	&asn_OP_SEQUENCE,
	asn_DEF_FullPrecisionInterframe_tags_1,
	sizeof(asn_DEF_FullPrecisionInterframe_tags_1)
		/sizeof(asn_DEF_FullPrecisionInterframe_tags_1[0]), /* 1 */
	asn_DEF_FullPrecisionInterframe_tags_1,	/* Same as above */
	sizeof(asn_DEF_FullPrecisionInterframe_tags_1)
		/sizeof(asn_DEF_FullPrecisionInterframe_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_FullPrecisionInterframe_1,
	3,	/* Elements count */
	&asn_SPC_FullPrecisionInterframe_specs_1	/* Additional specs */
};

