/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "ASN1Files/CEM v1.2.1.asn"
 */

#ifndef	_GPSDataUncertainty_H_
#define	_GPSDataUncertainty_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GPSDataUncertainty {
	GPSDataUncertainty_unavailable	= 201
} e_GPSDataUncertainty;

/* GPSDataUncertainty */
typedef long	 GPSDataUncertainty_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GPSDataUncertainty_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GPSDataUncertainty;
asn_struct_free_f GPSDataUncertainty_free;
asn_struct_print_f GPSDataUncertainty_print;
asn_constr_check_f GPSDataUncertainty_constraint;
ber_type_decoder_f GPSDataUncertainty_decode_ber;
der_type_encoder_f GPSDataUncertainty_encode_der;
xer_type_decoder_f GPSDataUncertainty_decode_xer;
xer_type_encoder_f GPSDataUncertainty_encode_xer;
oer_type_decoder_f GPSDataUncertainty_decode_oer;
oer_type_encoder_f GPSDataUncertainty_encode_oer;
per_type_decoder_f GPSDataUncertainty_decode_uper;
per_type_encoder_f GPSDataUncertainty_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GPSDataUncertainty_H_ */
#include "asn_internal.h"
