/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_MandatoryContainer_H_
#define	_MandatoryContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ConstellationID.h"
#include "SatellitePRN.h"
#include "Pseudorange.h"
#include "GPSDataUncertainty.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MandatoryContainer */
typedef struct MandatoryContainer {
	ConstellationID_t	 constellationID;
	SatellitePRN_t	 satellitePRN;
	Pseudorange_t	 pseudorange;
	GPSDataUncertainty_t	 pseudorangeUncertainty;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MandatoryContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MandatoryContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_MandatoryContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_MandatoryContainer_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MandatoryContainer_H_ */
#include <asn_internal.h>
