/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.1.asn"
 */

#include "OptionalContainer.h"

asn_TYPE_member_t asn_MBR_OptionalContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OptionalContainer, carrierPhase),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierPhase,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"carrierPhase"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OptionalContainer, carrierPhaseUncertainty),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPSDataUncertainty,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"carrierPhaseUncertainty"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OptionalContainer, doppler),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Doppler,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"doppler"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OptionalContainer, dopplerUncertainty),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPSDataUncertainty,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dopplerUncertainty"
		},
};
static const ber_tlv_tag_t asn_DEF_OptionalContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OptionalContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierPhase */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* carrierPhaseUncertainty */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* doppler */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* dopplerUncertainty */
};
asn_SEQUENCE_specifics_t asn_SPC_OptionalContainer_specs_1 = {
	sizeof(struct OptionalContainer),
	offsetof(struct OptionalContainer, _asn_ctx),
	asn_MAP_OptionalContainer_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OptionalContainer = {
	"OptionalContainer",
	"OptionalContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_OptionalContainer_tags_1,
	sizeof(asn_DEF_OptionalContainer_tags_1)
		/sizeof(asn_DEF_OptionalContainer_tags_1[0]), /* 1 */
	asn_DEF_OptionalContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_OptionalContainer_tags_1)
		/sizeof(asn_DEF_OptionalContainer_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_OptionalContainer_1,
	4,	/* Elements count */
	&asn_SPC_OptionalContainer_specs_1	/* Additional specs */
};

