/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "ASN1Files/CEM v1.2.1.asn"
 */

#ifndef	_Pseudorange_H_
#define	_Pseudorange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "INTEGER.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Pseudorange {
	Pseudorange_oneCentiMeter	= 1,
	Pseudorange_oneMeter	= 100,
	Pseudorange_unavailable	= 2900000001
} e_Pseudorange;

/* Pseudorange */
typedef INTEGER_t	 Pseudorange_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Pseudorange_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Pseudorange;
asn_struct_free_f Pseudorange_free;
asn_struct_print_f Pseudorange_print;
asn_constr_check_f Pseudorange_constraint;
ber_type_decoder_f Pseudorange_decode_ber;
der_type_encoder_f Pseudorange_encode_der;
xer_type_decoder_f Pseudorange_decode_xer;
xer_type_encoder_f Pseudorange_encode_xer;
oer_type_decoder_f Pseudorange_decode_oer;
oer_type_encoder_f Pseudorange_encode_oer;
per_type_decoder_f Pseudorange_decode_uper;
per_type_encoder_f Pseudorange_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Pseudorange_H_ */
#include "asn_internal.h"
