/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.2.2.asn"
 */

#include "SatelliteSignalInfo.h"

asn_TYPE_member_t asn_MBR_SatelliteSignalInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SatelliteSignalInfo, mandatoryContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MandatoryContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mandatoryContainer"
		},
	{ ATF_POINTER, 2, offsetof(struct SatelliteSignalInfo, optionalContainer),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OptionalContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"optionalContainer"
		},
	{ ATF_POINTER, 1, offsetof(struct SatelliteSignalInfo, uncertaintyContainer),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UncertaintyContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uncertaintyContainer"
		},
};
static const int asn_MAP_SatelliteSignalInfo_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_SatelliteSignalInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SatelliteSignalInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mandatoryContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* optionalContainer */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* uncertaintyContainer */
};
asn_SEQUENCE_specifics_t asn_SPC_SatelliteSignalInfo_specs_1 = {
	sizeof(struct SatelliteSignalInfo),
	offsetof(struct SatelliteSignalInfo, _asn_ctx),
	asn_MAP_SatelliteSignalInfo_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SatelliteSignalInfo_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SatelliteSignalInfo = {
	"SatelliteSignalInfo",
	"SatelliteSignalInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SatelliteSignalInfo_tags_1,
	sizeof(asn_DEF_SatelliteSignalInfo_tags_1)
		/sizeof(asn_DEF_SatelliteSignalInfo_tags_1[0]), /* 1 */
	asn_DEF_SatelliteSignalInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SatelliteSignalInfo_tags_1)
		/sizeof(asn_DEF_SatelliteSignalInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SatelliteSignalInfo_1,
	3,	/* Elements count */
	&asn_SPC_SatelliteSignalInfo_specs_1	/* Additional specs */
};

