/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.2.2.asn"
 */

#ifndef	_SatelliteSignalInfo_H_
#define	_SatelliteSignalInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MandatoryContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OptionalContainer;
struct UncertaintyContainer;

/* SatelliteSignalInfo */
typedef struct SatelliteSignalInfo {
	MandatoryContainer_t	 mandatoryContainer;
	struct OptionalContainer	*optionalContainer	/* OPTIONAL */;
	struct UncertaintyContainer	*uncertaintyContainer	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SatelliteSignalInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SatelliteSignalInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SatelliteSignalInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SatelliteSignalInfo_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OptionalContainer.h"
#include "UncertaintyContainer.h"

#endif	/* _SatelliteSignalInfo_H_ */
#include "asn_internal.h"
