/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.2.2.asn"
 */

#ifndef	_SignalID_H_
#define	_SignalID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignalID {
	SignalID_unavailable	= 0,
	SignalID_gpsL1	= 1,
	SignalID_gpsL2	= 2,
	SignalID_gpsL5	= 3,
	SignalID_gloG1	= 6,
	SignalID_gloG2	= 7,
	SignalID_gloG3	= 8,
	SignalID_galE1	= 11,
	SignalID_galE2	= 12,
	SignalID_galE5a	= 13,
	SignalID_galE5b	= 14,
	SignalID_galE6	= 15,
	SignalID_beiB1	= 18,
	SignalID_beiB2	= 19,
	SignalID_beiB3	= 20
} e_SignalID;

/* SignalID */
typedef long	 SignalID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SignalID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SignalID;
asn_struct_free_f SignalID_free;
asn_struct_print_f SignalID_print;
asn_constr_check_f SignalID_constraint;
ber_type_decoder_f SignalID_decode_ber;
der_type_encoder_f SignalID_encode_der;
xer_type_decoder_f SignalID_decode_xer;
xer_type_encoder_f SignalID_encode_xer;
oer_type_decoder_f SignalID_decode_oer;
oer_type_encoder_f SignalID_encode_oer;
per_type_decoder_f SignalID_decode_uper;
per_type_encoder_f SignalID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalID_H_ */
#include "asn_internal.h"
