/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "CEM v1.0.0.asn"
 */

#ifndef	_SignalStrenght_H_
#define	_SignalStrenght_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SignalStrenght */
typedef long	 SignalStrenght_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalStrenght;
asn_struct_free_f SignalStrenght_free;
asn_struct_print_f SignalStrenght_print;
asn_constr_check_f SignalStrenght_constraint;
ber_type_decoder_f SignalStrenght_decode_ber;
der_type_encoder_f SignalStrenght_encode_der;
xer_type_decoder_f SignalStrenght_decode_xer;
xer_type_encoder_f SignalStrenght_encode_xer;
oer_type_decoder_f SignalStrenght_decode_oer;
oer_type_encoder_f SignalStrenght_encode_oer;
per_type_decoder_f SignalStrenght_decode_uper;
per_type_encoder_f SignalStrenght_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalStrenght_H_ */
#include "asn_internal.h"
