/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CEM-PDU-Descriptions"
 * 	found in "ASN1Files/CEM v1.2.1.asn"
 */

#ifndef	_UncertaintyContainer_H_
#define	_UncertaintyContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GPSDataUncertainty.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UncertaintyContainer */
typedef struct UncertaintyContainer {
	GPSDataUncertainty_t	 pseudorangeUncertainty;
	GPSDataUncertainty_t	 carrierPhaseUncertainty;
	GPSDataUncertainty_t	 dopplerUncertainty;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UncertaintyContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UncertaintyContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_UncertaintyContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_UncertaintyContainer_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UncertaintyContainer_H_ */
#include "asn_internal.h"
